---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by GameTeckLab.
--- DateTime: 25. 12. 7. 오후 4:00
---

--- 매 프레임마다 호출됩니다.
--- @param Delta number 델타 타임
--- @return void

local ObjectDestroyerClass = require("w14_ObjectDestroyer")
local ObjectDestroyer = nil

--- 게임 시작 시 호출.
--- @return void
function BeginPlay()
    ObjectDestroyer = ObjectDestroyerClass:new(1, Obj)
end

--- 매 프레임마다 호출.
--- @param Delta number 델타 타임
--- @return void
function Tick(Delta)
    ObjectDestroyer:destroy_if_time_is_over(Delta)
end